[Rainmeter]
Update=500
BackgroundMode=2
SolidColor=0,0,0,1
OnRefreshAction=[!CommandMeasure MeasureAutoUpdate "Run"][!UpdateMeasure MeasureState][!UpdateMeasure MeasureTitlePlugin][!UpdateMeasure MeasureTitle][!UpdateMeter MeterLabel][!Redraw]
ContextTitle=Check Skin Update
ContextAction=["wscript.exe" "#UpdateScript#"]

[Variables]
LaunchScript=#CURRENTPATH#play.vbs
PlayPauseScript=#CURRENTPATH#playpause.vbs
PrevScript=#CURRENTPATH#previous.vbs
NextScript=#CURRENTPATH#next.vbs
UpdateScript=#CURRENTPATH#update.vbs
AutoCheckScript=#CURRENTPATH#autocheck.vbs
IconPlay=play.png
IconPause=15.png
; If play / pause icon looks reversed, change from 1 to 2
PlayingStateValue=1
ControlRefresh=[!UpdateMeasure MeasureState][!UpdateMeasure MeasureTitlePlugin][!UpdateMeasure MeasureTitle][!UpdateMeter MeterLabel][!Redraw]

[MeasureAutoUpdate]
Measure=Plugin
Plugin=RunCommand
Program=wscript.exe
Parameter="#AutoCheckScript#"
State=Hide
UpdateDivider=-1

[MeasureState]
Measure=Plugin
Plugin=MusicPlayer.dll
PlayerName=CloudMusic
PlayerType=State
IfCondition=(MeasureState=#PlayingStateValue#)
IfTrueAction=[!SetOption MeterPlay ImageName "#IconPause#"][!UpdateMeter MeterPlay][!Redraw]
IfFalseAction=[!SetOption MeterPlay ImageName "#IconPlay#"][!UpdateMeter MeterPlay][!Redraw]

[MeasureTitlePlugin]
Measure=Plugin
Plugin=MusicPlayer.dll
PlayerName=CloudMusic
PlayerType=TITLE

[MeasureTitle]
Measure=Script
ScriptFile=#CURRENTPATH#title_fallback.lua
UpdateDivider=2
DynamicVariables=1

[MeterLogo]
Meter=Image
ImageName=10.png
W=19
H=19
X=0
Y=2
LeftMouseUpAction=["wscript.exe" "#LaunchScript#"]
ToolTipText=Open CloudMusic

[MeterPrevious]
Meter=Image
ImageName=21.png
X=50
Y=4
LeftMouseUpAction=["wscript.exe" "#PrevScript#"]#ControlRefresh#
ToolTipText=Previous

[MeterPlay]
Meter=Image
ImageName=#IconPlay#
X=80
Y=4
LeftMouseUpAction=["wscript.exe" "#PlayPauseScript#"]#ControlRefresh#
ToolTipText=Play / Pause

[MeterNext]
Meter=Image
ImageName=12.png
X=110
Y=4
LeftMouseUpAction=["wscript.exe" "#NextScript#"]#ControlRefresh#
ToolTipText=Next

[MeterLabel]
Meter=String
X=150
Y=-1
FontColor=245,233,233
FontSize=11
FontFace=Microsoft YaHei
AntiAlias=1
StringStyle=BOLD
MeasureName=MeasureTitle
Text="%1"
ToolTipText=Now Playing

